 // ================= DROPDOWN OPTIONS =================

  const professions = [
    "Architects",
    "Interior Designers",
    "Landscape Designers",
    "Civil Engineers",
    "Structural Engineers",
    "Planners",
    "Town planners",
    "Urban planners",
    "City Planners",
    "Country Planners",
    "Interior Decorators",
    "Project Managers",
    "Surveyors",
    "Real estate agents",
  ];

  const contractorCategories = [
    "Builder",
    "General Contractor",
    "Remodelor",
    "Painters",
    "Flooring contractor",
    "Electrician",
    "Plumber",
    "HVAC",
    "Mechanical",
    "Pool Contractors",
    "Roofing",
    "Deck",
    "Patio",
    "Landcape",
    "Irrigation",
    "Fire alarm",
    "Fire Sprinkler",
    "Fence contractor",
    "Framer",
    "Drywall hangers",
    "Doors and windows",
    "Glass and Glazing",
    "Cabinets",
    "Counter tops",
    "Concrete",
    "Blacksmith",
  ];

  const supplierOptions = [
    "General Suppliers",
    "Plumbing",
    "Flooring",
    "Hardware",
    "Mechanical",
    "Electrical",
    "Roofing",
    "Gardening Supplies",
    "Irrigation Supplies",
    "Specialities",
    "Lumber",
    "Drywall",
    "Doors and windows",
    "Concrete",
  ];

  const serviceOptions = [
    "Trash",
    "Pest",
    "Weed and fertilizers (lawn care)",
    "Waterproofing",
    "Electrical Testing",
    "Smoke testing",
    "Construction Cleaning",
    "Water damage restoration",
    "Specialities",
    "Tool rentals",
    "Equipment rentals",
    "Vehcile rentals",
    "Dumpster",
    "Restorations",
    "Lab tests",
    "Surveyors",
  ];